<?php

class ConstantesController extends Controller
{

    public function actionIndex()
    {
        $array = array(
            'PRIORIDADE_NECESSARIA' => Constantes::PRIORIDADE_NECESSARIA,
            'PRIORIDADE_OPTATIVA' => Constantes::PRIORIDADE_OPTATIVA,
            'PRIORIDADE_LIVRE' => Constantes::PRIORIDADE_LIVRE,
            'LETRA_PRIORIDADE_NECESSARIA' => Constantes::LETRA_PRIORIDADE_NECESESARIA,
            'LETRA_PRIORIDADE_OPTATIVA' => Constantes::LETRA_PRIORIDADE_OPTATIVA,
            'LETRA_PRIORIDADE_LIVRE' => Constantes::LETRA_PRIORIDADE_LIVRE,
            'NOME_PRIORIDADE_NECESSARIA' => Constantes::NOME_PRIORIDADE_NECESSARIA,
            'NOME_PRIORIDADE_OPTATIVA' => Constantes::NOME_PRIORIDADE_OPTATIVA,
            'NOME_PRIORIDADE_LIVRE' => Constantes::NOME_PRIORIDADE_LIVRE,
            'NUMERO_MINIMO_DE_COMPONENTES_NECESSARIAS' => Constantes::NUMERO_MINIMO_DE_COMPONENTES_NECESSARIAS,
            'NUMERO_MINIMO_DE_COMPONENTES_OPTATIVAS' => Constantes::NUMERO_MINIMO_DE_COMPONENTES_OPTATIVAS,
            'NUMERO_MINIMO_DE_COMPONENTES_LIVRES' => Constantes::NUMERO_MINIMO_DE_COMPONENTES_LIVRES,
            'NUMERO_MINIMO_DE_COMPONENTES_PARA_CUMPRIR_HABILITACOES' => Constantes::NUMERO_MINIMO_DE_COMPONENTES_PARA_CUMPRIR_HABILITACOES(),
            'NUMERO_MAXIMO_DE_COMPONENTES_POR_HABILITACAO' => Constantes::NUMERO_MAXIMO_DE_COMPONENTES_POR_HABILITACAO(),
            // 'NUMERO_MINIMO_DE_COMPONENTES_OPTATIVAS_NOVAS_POR_HABILITACAO' => Constantes::NUMERO_MINIMO_DE_COMPONENTES_OPTATIVAS_NOVAS_POR_HABILITACAO(),
            'NUMERO_MINIMO_DE_COMPONENTES_NOVAS_POR_HABILITACAO' => Constantes::NUMERO_MINIMO_DE_COMPONENTES_NOVAS_POR_HABILITACAO,
            'NUMERO_MINIMO_DE_COMPONENTES_TOTAIS_SOMANDO_TODAS_HABILITACOES' => Constantes::NUMERO_MINIMO_DE_COMPONENTES_TOTAIS_SOMANDO_TODAS_HABILITACOES(),
            'NUMERO_MAXIMO_DE_COMPONENTES_TOTAIS_SOMANDO_TODAS_HABILITACOES' => Constantes::NUMERO_MAXIMO_DE_COMPONENTES_TOTAIS_SOMANDO_TODAS_HABILITACOES(),
            'NUMERO_DE_COMPONENTES_OBRIGATORIOAS_PARA_EXTENSAO_E_APERFEICOAMENTO' => Constantes::NUMERO_DE_COMPONENTES_OBRIGATORIOAS_PARA_EXTENSAO_E_APERFEICOAMENTO,
            'STRING_COMPONENTES_OBRIGATORIOS_PARA_EXTENSAO_E_APERFEICOAMENTO' => Constantes::STRING_COMPONENTES_OBRIGATORIOS_PARA_EXTENSAO_E_APERFEICOAMENTO,
            'NUMERO_DE_COMPONENTES_LIVRES_PARA_EXTENSAO' => Constantes::NUMERO_DE_COMPONENTES_LIVRES_PARA_EXTENSAO,
            'NUMERO_DE_COMPONENTES_LIVRES_PARA_APERFEICOAMENTO' => Constantes::NUMERO_DE_COMPONENTES_LIVRES_PARA_APERFEICOAMENTO,
            'COMPONENTES_OBRIGATORIAS_PARA_ESPECIALIZACAO' => Constantes::COMPONENTES_OBRIGATORIAS_PARA_ESPECIALIZACAO(),
            'COMPONENTES_OBRIGATORIAS_PARA_EXTENSAO_E_APERFEICOAMENTO' => Constantes::COMPONENTES_OBRIGATORIAS_PARA_EXTENSAO_E_APERFEICOAMENTO(),
            'ORDINAIS' => Constantes::ORDINAIS(),
            'HABILITACOES' => $this->processarHabilitacoes(),
            'COMPONENTE_DESENVOLVIMENTO_DE_PROJETO_INTEGRADOR' => Constantes::COMPONENTE_DESENVOLVIMENTO_DE_PROJETO_INTEGRADOR,
        );

        $this->respostaJSON(json_encode($array));
    }

    private function processarHabilitacoes()
    {
        $habilitacoes = Habilitacao::findAllValid();
        return array_map(function($habilitacao) {
            return [ 'id' => $habilitacao->id ];
        }, $habilitacoes);
    }

}
